image: docker:latest

services:
  - docker:dind

# DOCKER_DRIVER: Requires when sharing folder with running containers
# IMAGE_NAME   : Name of the image to be used for all refs (branches and tags)
variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: hello-world

# Stages: sequential stages for this project to execute one after another
stages:
  - build_image
  - test_image
  - tag_image

# Bring command shortcuts like 'docker_build_push' made in file 'prepare'
before_script:
- source prepare

# Build and push image using oneshot command with branch name as image name
# (does not used long conventional coding like 'docker build -t test .' ...)
build_image:
  stage: build_image
  script:
    - docker_build_push $IMAGE_NAME
    - docker_tag_push $IMAGE_NAME compiled

# Test image by executing its code (docker pull followed with docker run)
test_image:
  stage: test_image
  script:
    - docker_test_image $IMAGE_NAME compiled

# Tag image as latest on branch name when previous test is passed
tag_image:
  stage: tag_image
  script:
    - docker_tagg_image $IMAGE_NAME compiled latest
