image: docker:latest

services:
  - docker:dind

# DOCKER_DRIVER: Requires when sharing folder with running containers
# IMAGE_NAME   : Name of the branche or tag name
variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: $CI_COMMIT_REF_SLUG

# Stages: sequential stages for this project to execute one after another
stages:
  - build
  - test
  - deploy

# Bring command shortcuts like 'docker_build_push' made in file 'prepare'
before_script:
- source prepare

# Build and push image using oneshot command with branch name as image name
# (does not used long conventional coding like 'docker build -t test .' ...)
build:
  stage: build
  script:
    - docker_build_push $IMAGE_NAME
    - docker_tag_push $IMAGE_NAME compiled
  only:
    - tags
    - branch

# Test image by executing its code (docker pull followed with docker run)
test:
  stage: test
  script:
    - docker_test_image $IMAGE_NAME compiled
  environment:
    name: testing
  only:
    - tags
    - branch

# Tag image as staging on branch name when previous test is passed
deploy_staging:
  stage: deploy
  script:
    - docker_test_image $IMAGE_NAME compiled
    - docker_tagg_image $IMAGE_NAME compiled staging
  environment:
    name: staging
    url: https://gitlab.com/$CI_PROJECT_PATH/pipelines
  only:
    - tags
    - master

# Tag image as latest on branch name when previous test is passed
deploy_prod:
  stage: deploy
  script:
    - docker_test_image $IMAGE_NAME staging
    - docker_tagg_image $IMAGE_NAME staging latest
  when: manual
  environment:
    name: production
    url: https://gitlab.com/$CI_PROJECT_PATH/pipelines
  when: manual
  only:
    - master
